In [1]:
import tensorflow as tf

In [2]:
#建立計算圖
ts_c = tf.constant(2, name='ts_c')
ts_x = tf.Variable(ts_c+5, name='ts_x')
# Session 代表用戶端和執行裝置之間建立連結
sess = tf.Session() # 開啟 session, 並開始執行計算圖
init = tf.global_variables_initializer()
sess.run(init)
print('ts_c=', sess.run(ts_c))
print('ts_x=', sess.run(ts_x))
print('ts_c=', ts_c.eval(session=sess)) # runs one step
print('ts_x=', ts_x.eval(session=sess)) # runs one step
sess.close() # 關閉 session, 並結束執行計算圖

ts_c= 2
ts_x= 7
ts_c= 2
ts_x= 7


In [3]:
a = tf.constant(2, name='a')
x = tf.Variable(ts_c+5, name='x')

with tf.Session() as sess:  # with 語法開啟 session, 避免前述方法忘記關閉 session
    init = tf.global_variables_initializer()
    sess.run(init)
    print('a = ', sess.run(a))
    print('x = ',sess.run(x))

a =  2
x =  7


In [20]:
#TensorFlow has two ways to evaluate part of graph: Session.run on a list of variables and Tensor.eval.
#The most important difference is that you can use sess.run() to fetch the values of many tensors in the same step:

t = tf.constant(42.0)
u = tf.constant(37.0)
tu = tf.multiply(t, u)
ut = tf.add(u, t)

with tf.Session() as sess: # with 語法開啟 session, 避免前述方法忘記關閉 session
    print(tu.eval())  # runs one step
    print(ut.eval())  # runs one step
    print(sess.run([tu, ut])) # evaluates both tensors in a single step
    

1554.0
79.0
[1554.0, 79.0]


## placeholder: 先宣告變數，等執行設計圖時，才設定數值

In [5]:
width = tf.placeholder("int32", name='width')
height = tf.placeholder("int32", name='height')
area = tf.multiply(width, height, name='area') #相乘

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area = ', sess.run(area, feed_dict={width: 6, height: 8}))

area =  48


## 1-D Tensor: Vector

In [6]:
ts_X = tf.Variable([0.4,0.2,0.4])
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X=sess.run(ts_X)
    print(X)

[ 0.40000001  0.2         0.40000001]


In [7]:
print(X.shape) # 3 個數值

(3,)


## 2-D Tensor: Mactix 

In [8]:
ts_X = tf.Variable([[0.4,0.2,0.4]])
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X=sess.run(ts_X)
    print(X)

[[ 0.40000001  0.2         0.40000001]]


In [9]:
print(X.shape) # (1 筆資料， 每一筆有 3 個數值)

(1, 3)


In [10]:
W = tf.Variable([[-0.5,-0.2],
                [-0.3, 0.4],
                [-0.5, 0.2]])
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    W_array=sess.run(W)
    print(W_array)

[[-0.5        -0.2       ]
 [-0.30000001  0.40000001]
 [-0.5         0.2       ]]


In [11]:
print(W_array.shape) # (3 筆資料， 每一筆有 2 個數值)

(3, 2)


## 矩陣運算: 乘法

In [12]:
# 矩陣運算: 乘法
X = tf.Variable([[1.,1.,1.]])
W = tf.Variable([[-0.5,-0.2],
                [-0.3, 0.4],
                [-0.5, 0.2]])
XW = tf.matmul(X,W)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    XW_array=sess.run(XW)
    print(XW_array)

[[-1.29999995  0.40000001]]


## 矩陣運算: 加法

In [13]:
b = tf.Variable([[0.1,0.2]])
XW = tf.Variable([[-1.3,0.4]])
Sum = XW+b

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('Sim:')
    print(sess.run(Sum))

Sim:
[[-1.19999993  0.60000002]]


## 矩陣運算: 乘法和加法

In [14]:
X = tf.Variable([[1.,1.,1.]])
W = tf.Variable([[-0.5,-0.2],
                [-0.3, 0.4],
                [-0.5, 0.2]])
b = tf.Variable([[0.1,0.2]])

XWb = tf.matmul(X,W)+b

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:')
    print(sess.run(XWb))

XWb:
[[-1.19999993  0.60000002]]
